### ISSUE TITLE
Catch failed plotly downloads

### ISSUE THREAD

**Issue by etwuerschmidt** [etwuerschmidt/song-roulette#44]
`2020-05-01T17:51:40.404796+00:00 app[web.1]: INFO: [2020-05-01 17:51:40,404][analysis.py|graph_view_save|54] Image successfully created and hosted at https://plotly.com/~etwuerschmidt/230/
2020-05-01T17:51:51.146057+00:00 app[web.1]: ERROR: [2020-05-01 17:51:51,143][messaging.py|post_block|32] The request to the Slack API failed.
2020-05-01T17:51:51.146127+00:00 app[web.1]: The server responded with: {'ok': False, 'error': 'invalid_blocks', 'response_metadata': {'messages': ['[ERROR] downloading image failed [json-pointer:/blocks/0/image_url]']}}
2020-05-01T17:51:51.146138+00:00 app[web.1]: Traceback (most recent call last):
2020-05-01T17:51:51.146139+00:00 app[web.1]:   File "/app/slackapp/clients/messaging.py", line 30, in post_block
2020-05-01T17:51:51.146139+00:00 app[web.1]:     channel=self.channel if not channel else channel, blocks=blocks)
2020-05-01T17:51:51.146145+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/slack/web/client.py", line 559, in chat_postMessage
2020-05-01T17:51:51.146206+00:00 app[web.1]:     return self.api_call("chat.postMessage", json=kwargs)
2020-05-01T17:51:51.146403+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/slack/web/base_client.py", line 171, in api_call
2020-05-01T17:51:51.146404+00:00 app[web.1]:     return self._event_loop.run_until_complete(future)
2020-05-01T17:51:51.146405+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
2020-05-01T17:51:51.146405+00:00 app[web.1]:     return future.result()
2020-05-01T17:51:51.146406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/slack/web/base_client.py", line 226, in _send
2020-05-01T17:51:51.146406+00:00 app[web.1]:     return SlackResponse(**{**data, **res}).validate()
2020-05-01T17:51:51.146407+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/slack/web/slack_response.py", line 176, in validate
2020-05-01T17:51:51.146407+00:00 app[web.1]:     raise e.SlackApiError(message=msg, response=self)
2020-05-01T17:51:51.146408+00:00 app[web.1]: slack.errors.SlackApiError: The request to the Slack API failed.
2020-05-01T17:51:51.146435+00:00 app[web.1]: The server responded with: {'ok': False, 'error': 'invalid_blocks', 'response_metadata': {'messages': ['[ERROR] downloading image failed [json-pointer:/blocks/0/image_url]']}}`

**Comment by etwuerschmidt** [comment]
This looks like a Slack internal error - couldn't find anything online to debug this further. Added a fallback message to share the image url
